####################################################################################################
# Copyright (c) 2023 Bahman Movaqar
#
# This file is part of lemmy-synapse.
# lemmy-synapse is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# lemmy-synapse is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with lemmy-synapse.
# If not, see <https://www.gnu.org/licenses/>.
####################################################################################################

---

- name: "persist-configs ➤➤➤ Ensure variables are set"
  ansible.builtin.assert:
    that:
      - lemmy_synapse_installation_directory
      - postgres_service_name
      - postgres_port
      - lemmy_synapse_postgres_user
      - lemmy_synapse_postgres_password
      - lemmy_network

- name: "persist-configs ➤➤➤ postgres-exporter DATA_SOURCE_NAME"
  ansible.builtin.lineinfile:
    path: "{{ lemmy_synapse_installation_directory }}/postgres-exporter/postgres-exporter.conf"

    regexp: "^PG_EXPORTER_DATA_SOURCE_NAME"
    line: "PG_EXPORTER_DATA_SOURCE_NAME=postgresql://\
      {{ lemmy_synapse_postgres_user }}:{{ lemmy_synapse_postgres_password }}\
      @{{ postgres_service_name }}:{{ postgres_port }}/postgres?sslmode=disable"

    insertafter: EOF
    create: true
    state: present

- name: "persist-configs ➤➤➤ lemmy-synapse LEMMY_SYNAPSE_NETWORK"
  ansible.builtin.lineinfile:
    path: "{{ lemmy_synapse_installation_directory }}/lemmy-synapse.conf"

    regexp: "^LEMMY_SYNAPSE_NETWORK"
    line: "LEMMY_SYNAPSE_NETWORK={{ lemmy_network }}"

    insertafter: EOF
    create: true
    state: present
