####################################################################################################
# Copyright (c) 2023 Bahman Movaqar
#
# This file is part of lemmy-synapse.
# lemmy-synapse is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# lemmy-synapse is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with lemmy-synapse.
# If not, see <https://www.gnu.org/licenses/>.
####################################################################################################

---

- name: "restart ➤➤➤ Ensure variables are set"
  ansible.builtin.assert:
    that:
      - lemmy_synapse_installation_directory

- name: "restart ➤➤➤ Shut down the cluster"
  ansible.builtin.command:
    cmd: >-
      {{ lemmy_synapse_installation_directory }}/lemmy-synapse down
  register: _result
  changed_when: _result is success

- name: "restart ➤➤➤ Start the cluster"
  ansible.builtin.command:
    cmd: >-
      {{ lemmy_synapse_installation_directory }}/lemmy-synapse up
  register: _result
  changed_when: _result is success
