####################################################################################################
# Copyright (c) 2023 Bahman Movaqar
#
# This file is part of lemmy-synapse.
# lemmy-synapse is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# lemmy-synapse is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with lemmy-synapse.
# If not, see <https://www.gnu.org/licenses/>.
####################################################################################################

---

- name: Install and configure lemmy-synapse
  hosts: all
  become: true

  tasks:
    - name: Read in "installation-config.yml"
      ansible.builtin.include_vars:
        file: "{{ lemmy_synapse_installation_config_path }}"

    - name: Ensure configuration options are set
      ansible.builtin.assert:
        that:
          - lemmy_synapse_archive_path
          - lemmy_synapse_installation_directory
          - postgres_hostname
          - postgres_port
          - postgres_admin_user
          - postgres_admin_password
          - postgres_service_name
          - lemmy_synapse_postgres_user
          - lemmy_synapse_postgres_password
          - lemmy_network
          - lemmy_synapse_dashboards_path

    - name: Copy lemmy-synapse to the remote host
      block:
        - name: "copy ➤➤➤ Ensure installation directory exists"
          ansible.builtin.file:
            path: "{{ lemmy_synapse_installation_directory }}"
            state: directory

        - name: "copy ➤➤➤ Extract lemmy-synapse archive"
          ansible.builtin.unarchive:
            src: "{{ lemmy_synapse_archive_path }}"
            dest: "{{ lemmy_synapse_installation_directory }}"

    - name: "Configure PostgreSQL"
      ansible.builtin.import_tasks:
        file: "tasks/configure-postgresql.yml"

    - name: Persist lemmy-synapse configuration
      ansible.builtin.import_tasks:
        file: "tasks/persist-configs.yml"

    - name: Restart lemmy-synapse cluster
      ansible.builtin.import_tasks:
        file: "tasks/restart.yml"

    - name: "Configure Grafana"
      ansible.builtin.import_tasks:
        file: "tasks/configure-grafana.yml"

    - name: "Post-installation information"
      ansible.builtin.debug:
        msg: >-
          lemmy-synapse has been successfully installed on your server.
          You can now use an SSH tunnel to access your dashboards (see README.)
