####################################################################################################
# Copyright (c) 2023 Bahman Movaqar
#
# This file is part of lemmy-synapse.
# lemmy-synapse is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# lemmy-synapse is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with lemmy-synapse.
# If not, see <https://www.gnu.org/licenses/>.
####################################################################################################

---
version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.48.0
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=30d"
      - "--log.level=debug"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus-data:/prometheus"
    networks:
      - lemmy
    restart: always

  grafana:
    image: grafana/grafana:10.2.2
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - "grafana-data:/var/lib/grafana"
    networks:
      - lemmy
    restart: always

  node-exporter:
    image: prom/node-exporter:v1.7.0
    command: "${NODE_EXPORTER_OPTIONS}"
    volumes:
      - "/:/host:ro,rslave"
    networks:
      - lemmy
    pid: host
    restart: always

  postgresql-exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    command:
      - "--log.level=debug"
    environment:
      - DATA_SOURCE_NAME=${PG_EXPORTER_DATA_SOURCE_NAME}
    networks:
      - lemmy
    restart: always

  redis:
    image: redis:7.2.3
    command:
      - "redis-server"
      - "--save 60 1"
      - "--loglevel warning"
    volumes:
      - "redis-data:/data"
    networks:
      - lemmy
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker:/var/lib/docker:ro"
    devices:
      - "/dev/kmsg:/dev/kmsg"
    privileged: true
    depends_on:
      - redis
    networks:
      - lemmy
    restart: always

  loki:
    image: grafana/loki:2.9.2
    command:
      - "-config.file=/etc/loki/config.yaml"
      - "-target=all"
    volumes:
      - "./loki/config.yaml:/etc/loki/config.yaml"
      - "loki-data:/var/lib/loki"
    user: "${UID}:${GID}"
    networks:
      - lemmy
    restart: always

  promtail:
    image: grafana/promtail:2.9.2
    command:
      - "-config.file=/etc/promtail/config.yaml"
    volumes:
      - "./promtail/config.yaml:/etc/promtail/config.yaml"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/log/journal:/var/log/journal"
    networks:
      - lemmy

volumes:
  prometheus-data:
  grafana-data:
  redis-data:
  loki-data:

networks:
  lemmy:
    name: ${LEMMY_SYNAPSE_NETWORK}
    external: true
